using ISO11820.UI.Tests.Infrastructure;
using Xunit;
using Xunit.Abstractions;

namespace ISO11820.UI.Tests.Tests;

/// <summary>
/// 第十二部分：数据导出验收测试
/// </summary>
public class TC09_Export : UITestBase
{
    private readonly ITestOutputHelper _output;
    private readonly string _baseDirectory;

    public TC09_Export(ITestOutputHelper output)
    {
        _output = output;
        _baseDirectory = @"D:\ISO11820"; // 从 appsettings.json 读取
    }

    [Fact(DisplayName = "12.1 CSV 导出 — 自动生成")]
    public void Export_CsvAutoGenerated()
    {
        StartAndLoginViaSignal();
        var window = GetMainWindow(); Assert.NotNull(window);

        // 完成一次试验
        RunFullTestCycle(window, "EXP-01", "T01");
        Thread.Sleep(2000);

        // 检查 CSV 文件是否生成
        var csvDir = Path.Combine(_baseDirectory, "TestData", "EXP-01");
        if (Directory.Exists(csvDir))
        {
            var csvFiles = Directory.GetFiles(csvDir, "*.csv", SearchOption.AllDirectories);
            _output.WriteLine($"  CSV 文件数: {csvFiles.Length}");
            foreach (var f in csvFiles)
            {
                _output.WriteLine($"    {f}");
                var content = File.ReadAllText(f);
                var lines = content.Split('\n', StringSplitOptions.RemoveEmptyEntries);
                _output.WriteLine($"    行数: {lines.Length}");
                if (lines.Length > 0)
                    _output.WriteLine($"    首行: {lines[0]}");
            }
        }
        else
        {
            _output.WriteLine($"  CSV 目录不存在: {csvDir}");
            _output.WriteLine("  （可能配置了不同的输出路径）");
        }

        Capture("12.1_CSV导出");
        _output.WriteLine("✅ CSV 导出测试完成");
    }

    [Fact(DisplayName = "12.1.3 CSV 格式 — 包含5通道列")]
    public void Export_CsvFormat()
    {
        StartAndLoginViaSignal();
        var window = GetMainWindow(); Assert.NotNull(window);

        RunFullTestCycle(window, "EXP-02", "T02");
        Thread.Sleep(2000);

        var csvDir = Path.Combine(_baseDirectory, "TestData", "EXP-02");
        if (Directory.Exists(csvDir))
        {
            var csvFiles = Directory.GetFiles(csvDir, "*.csv", SearchOption.AllDirectories);
            if (csvFiles.Length > 0)
            {
                var header = File.ReadLines(csvFiles[0]).FirstOrDefault();
                _output.WriteLine($"  CSV 表头: {header}");

                if (header != null)
                {
                    // 验证包含5个温度列
                    Assert.Contains("Time", header);
                    Assert.Contains("Temp1", header);
                    Assert.Contains("Temp2", header);
                }
            }
        }

        _output.WriteLine("✅ CSV 格式验证完成");
    }

    [Fact(DisplayName = "12.2 Excel 导出")]
    public void Export_Excel()
    {
        StartAndLoginViaSignal();
        var window = GetMainWindow(); Assert.NotNull(window);

        RunFullTestCycle(window, "EXP-03", "T03");
        Thread.Sleep(2000);

        // 检查 Excel 文件
        var reportDir = Path.Combine(_baseDirectory, "Reports");
        if (Directory.Exists(reportDir))
        {
            var xlsxFiles = Directory.GetFiles(reportDir, "*.xlsx", SearchOption.AllDirectories);
            _output.WriteLine($"  Excel 文件数: {xlsxFiles.Length}");
            foreach (var f in xlsxFiles)
            {
                var fi = new FileInfo(f);
                _output.WriteLine($"    {f} ({fi.Length} bytes)");
            }
        }
        else
        {
            _output.WriteLine($"  报告目录不存在: {reportDir}");
        }

        Capture("12.2_Excel导出");
        _output.WriteLine("✅ Excel 导出测试完成");
    }

    [Fact(DisplayName = "12.3 PDF 导出")]
    public void Export_Pdf()
    {
        StartAndLoginViaSignal();
        var window = GetMainWindow(); Assert.NotNull(window);

        RunFullTestCycle(window, "EXP-04", "T04");
        Thread.Sleep(2000);

        // 检查 PDF 文件
        var reportDir = Path.Combine(_baseDirectory, "Reports");
        if (Directory.Exists(reportDir))
        {
            var pdfFiles = Directory.GetFiles(reportDir, "*.pdf", SearchOption.AllDirectories);
            _output.WriteLine($"  PDF 文件数: {pdfFiles.Length}");
            foreach (var f in pdfFiles)
            {
                var fi = new FileInfo(f);
                _output.WriteLine($"    {f} ({fi.Length} bytes)");
            }
        }

        Capture("12.3_PDF导出");
        _output.WriteLine("✅ PDF 导出测试完成");
    }

    [Fact(DisplayName = "12.4 目录自动创建")]
    public void Export_AutoCreateDirectories()
    {
        StartAndLoginViaSignal();
        var window = GetMainWindow(); Assert.NotNull(window);

        var timestamp = DateTime.Now.ToString("HHmmss");
        RunFullTestCycle(window, $"EXP-{timestamp}", "T05");
        Thread.Sleep(2000);

        // 验证目录结构
        var expectedTestDataDir = Path.Combine(_baseDirectory, "TestData", $"EXP-{timestamp}");
        var expectedReportsDir = Path.Combine(_baseDirectory, "Reports");

        _output.WriteLine($"  TestData 目录: {(Directory.Exists(expectedTestDataDir) ? "已创建" : "未创建")}");
        _output.WriteLine($"  Reports 目录: {(Directory.Exists(expectedReportsDir) ? "已创建" : "未创建")}");

        Capture("12.4_目录自动创建");
        _output.WriteLine("✅ 目录自动创建验证完成");
    }

    // ═══════════════════════════════════════════════════
    //  辅助方法
    // ═══════════════════════════════════════════════════

    private void RunFullTestCycle(FlaUI.Core.AutomationElements.Window window, string productId, string testId)
    {
        CreateNewTest(window, productId, testId);
        window = GetMainWindow() ?? window;
        ClickButtonBySignal("click_start_heating");
        WaitStrategies.TryWaitForLabelText(window, "当前状态", "就绪", TimeSpan.FromSeconds(30));
        ClickButtonBySignal("click_start_recording");
        Thread.Sleep(5000);
        ClickButtonBySignal("click_stop_recording");
        Thread.Sleep(2000);
    }

    }
